version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: marketplace_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: marketplace_db
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - marketplace_network

  # FastAPI Backend
  backend:
    build: .
    container_name: marketplace_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/marketplace_db?authSource=admin
      - DATABASE_NAME=marketplace_db
      - SECRET_KEY=your-super-secret-jwt-key-change-this-in-production
      - DEBUG=True
    depends_on:
      - mongodb
    volumes:
      - .:/app
    networks:
      - marketplace_network

  # MongoDB Admin UI (optional)
  mongo-express:
    image: mongo-express:latest
    container_name: marketplace_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - marketplace_network

volumes:
  mongodb_data:

networks:
  marketplace_network:
    driver: bridge